name: GitHub Readme YouTube Cards

on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the GitHub Readme YouTube Cards action
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCOLkBOWpSVd7u81ueXG-bmQ
